-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  legal_name text,
  tax_id text,
  email text UNIQUE,
  phone text,
  country_code character NOT NULL DEFAULT 'MX'::bpchar CHECK (char_length(country_code) = 2),
  currency_code character NOT NULL DEFAULT 'MXN'::bpchar CHECK (char_length(currency_code) = 3),
  timezone text NOT NULL DEFAULT 'America/Mexico_City'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  address text,
  city text,
  state text,
  postal_code text,
  country_code character NOT NULL DEFAULT 'MX'::bpchar CHECK (char_length(country_code) = 2),
  email text,
  phone text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  opening_time time without time zone,
  closing_time time without time zone,
  foodbot_sync_enabled boolean DEFAULT true,
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_organization_fk FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.catalog_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  CONSTRAINT catalog_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.catalog_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  catalog_type_id uuid NOT NULL,
  code text NOT NULL CHECK (code ~ '^[A-Z][A-Z0-9_]*$'::text),
  name text NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  color text,
  icon text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT catalog_values_pkey PRIMARY KEY (id),
  CONSTRAINT catalog_values_catalog_type_fk FOREIGN KEY (catalog_type_id) REFERENCES public.catalog_types(id)
);
CREATE TABLE public.external_sales_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  source text NOT NULL CHECK (source = upper(source)),
  report_date date NOT NULL,
  total_orders integer NOT NULL DEFAULT 0 CHECK (total_orders >= 0),
  total_sales numeric NOT NULL DEFAULT 0 CHECK (total_sales >= 0::numeric),
  average_ticket numeric NOT NULL DEFAULT 0 CHECK (average_ticket >= 0::numeric),
  raw_data jsonb CHECK (raw_data IS NULL OR jsonb_typeof(raw_data) = 'object'::text),
  imported_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT external_sales_reports_pkey PRIMARY KEY (id),
  CONSTRAINT fk_external_sales_reports_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_external_sales_reports_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.external_sales_report_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  report_id uuid NOT NULL,
  product_id uuid,
  source_product_code text NOT NULL CHECK (source_product_code = upper(source_product_code)),
  source_product_name text NOT NULL CHECK (length(TRIM(BOTH FROM source_product_name)) > 0),
  orders_count integer NOT NULL DEFAULT 0 CHECK (orders_count >= 0),
  quantity_sold integer NOT NULL DEFAULT 0 CHECK (quantity_sold >= 0),
  total_sales numeric NOT NULL DEFAULT 0 CHECK (total_sales >= 0::numeric),
  raw_data jsonb CHECK (raw_data IS NULL OR jsonb_typeof(raw_data) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT external_sales_report_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_external_sales_report_items_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_external_sales_report_items_report FOREIGN KEY (report_id) REFERENCES public.external_sales_reports(id),
  CONSTRAINT fk_external_sales_report_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_code text NOT NULL UNIQUE CHECK (product_code = upper(product_code)),
  name text NOT NULL CHECK (length(TRIM(BOTH FROM name)) > 0),
  description text,
  category_id uuid NOT NULL,
  unit_id uuid NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cost_price numeric,
  items_per_box integer,
  box_price numeric,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES public.catalog_values(id),
  CONSTRAINT fk_products_unit FOREIGN KEY (unit_id) REFERENCES public.catalog_values(id)
);
CREATE TABLE public.branch_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  current_stock numeric NOT NULL DEFAULT 0,
  minimum_stock numeric NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0::numeric),
  maximum_stock numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branch_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT fk_branch_inventory_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_branch_inventory_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_branch_inventory_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  movement_type_id uuid NOT NULL,
  quantity numeric NOT NULL CHECK (quantity <> 0::numeric),
  previous_stock numeric,
  current_stock numeric,
  reference_type text CHECK (reference_type IS NULL OR reference_type = upper(reference_type)),
  reference_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_inventory_movements_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_inventory_movements_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_inventory_movements_product FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT fk_inventory_movements_movement_type FOREIGN KEY (movement_type_id) REFERENCES public.catalog_values(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  display_name text,
  email text,
  phone text,
  avatar_url text,
  branch_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT fk_profiles_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_profiles_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z][A-Z0-9_]*$'::text),
  name text NOT NULL UNIQUE,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profile_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  role_id uuid NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_roles_pkey PRIMARY KEY (id),
  CONSTRAINT fk_profile_roles_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_profile_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  sale_number text NOT NULL,
  customer_id uuid,
  created_by uuid NOT NULL,
  status_id uuid NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0 CHECK (subtotal >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sales_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_sales_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_sales_created_by FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_sales_status FOREIGN KEY (status_id) REFERENCES public.catalog_values(id)
);
CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  sale_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit_cost numeric NOT NULL CHECK (unit_cost >= 0::numeric),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sale_items_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  sale_id uuid NOT NULL,
  payment_method_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  received_amount numeric,
  change_amount numeric DEFAULT 0 CHECK (change_amount >= 0::numeric),
  payment_reference text,
  authorization_code text,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payments_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_payments_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_payments_sale FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT fk_payments_payment_method FOREIGN KEY (payment_method_id) REFERENCES public.catalog_values(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  supplier_code text NOT NULL,
  name text NOT NULL,
  legal_name text,
  tax_id text,
  contact_name text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  postal_code text,
  country_code character NOT NULL DEFAULT 'MX'::bpchar,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_suppliers_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  purchase_order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity_ordered numeric NOT NULL CHECK (quantity_ordered > 0::numeric),
  quantity_received numeric NOT NULL DEFAULT 0,
  unit_cost numeric NOT NULL CHECK (unit_cost >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_purchase_order_items_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_purchase_order_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.expense_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  expense_id uuid NOT NULL,
  uploaded_by uuid,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size bigint CHECK (file_size IS NULL OR file_size >= 0),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_expense_attachments_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_expense_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.waste_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  waste_number text NOT NULL,
  reported_by uuid NOT NULL,
  status_id uuid NOT NULL,
  reason_id uuid NOT NULL,
  waste_date date NOT NULL,
  total_cost numeric NOT NULL DEFAULT 0 CHECK (total_cost >= 0::numeric),
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT waste_records_pkey PRIMARY KEY (id),
  CONSTRAINT fk_waste_records_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_waste_records_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_waste_records_reported_by FOREIGN KEY (reported_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_waste_records_status FOREIGN KEY (status_id) REFERENCES public.catalog_values(id),
  CONSTRAINT fk_waste_records_reason FOREIGN KEY (reason_id) REFERENCES public.catalog_values(id)
);
CREATE TABLE public.waste_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  waste_record_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit_cost_at_time numeric NOT NULL CHECK (unit_cost_at_time >= 0::numeric),
  subtotal_loss numeric NOT NULL CHECK (subtotal_loss >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT waste_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_waste_items_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_waste_items_record FOREIGN KEY (waste_record_id) REFERENCES public.waste_records(id),
  CONSTRAINT fk_waste_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.transfer_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  source_branch_id uuid NOT NULL,
  destination_branch_id uuid NOT NULL,
  transfer_number text NOT NULL,
  status_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  received_by uuid,
  transfer_date date NOT NULL,
  received_date date,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transfer_orders_pkey PRIMARY KEY (id),
  CONSTRAINT fk_transfer_orders_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_transfer_orders_source_branch FOREIGN KEY (source_branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_transfer_orders_destination_branch FOREIGN KEY (destination_branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_transfer_orders_status FOREIGN KEY (status_id) REFERENCES public.catalog_values(id),
  CONSTRAINT fk_transfer_orders_requested_by FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_transfer_orders_received_by FOREIGN KEY (received_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.transfer_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  transfer_order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity_requested numeric NOT NULL CHECK (quantity_requested > 0::numeric),
  quantity_sent numeric NOT NULL DEFAULT 0 CHECK (quantity_sent >= 0::numeric),
  quantity_received numeric NOT NULL DEFAULT 0 CHECK (quantity_received >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transfer_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_transfer_items_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_transfer_items_order FOREIGN KEY (transfer_order_id) REFERENCES public.transfer_orders(id),
  CONSTRAINT fk_transfer_items_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.foodbot_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  foodbot_name text NOT NULL UNIQUE CHECK (length(TRIM(BOTH FROM foodbot_name)) > 0),
  product_id uuid NOT NULL,
  deduction_quantity numeric NOT NULL DEFAULT 1.0000 CHECK (deduction_quantity > 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT foodbot_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_foodbot_mappings_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'ENVIADA'::text CHECK (status = ANY (ARRAY['ENVIADA'::text, 'ACEPTADA'::text, 'RECHAZADA'::text, 'ENTREGADA'::text])),
  justification text,
  order_data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_id uuid NOT NULL,
  date date NOT NULL,
  category text NOT NULL,
  concept text NOT NULL,
  establishment text NOT NULL,
  amount numeric NOT NULL,
  folio text,
  payment_method text NOT NULL,
  responsible text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.audit_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  started_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'IN_PROGRESS'::text CHECK (status = ANY (ARRAY['IN_PROGRESS'::text, 'COMPLETED'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_audit_sessions_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_audit_sessions_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT fk_audit_sessions_started_by FOREIGN KEY (started_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_counts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  expected_stock numeric,
  counted_stock numeric NOT NULL CHECK (counted_stock >= 0::numeric),
  difference numeric,
  evidence_photo_url text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_counts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_audit_counts_session FOREIGN KEY (session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT fk_audit_counts_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_audit_counts_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['INFO'::text, 'SUCCESS'::text, 'WARNING'::text, 'ALERT'::text])),
  reference_type text,
  reference_id uuid,
  is_read boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_notifications_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_notifications_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.branch_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL UNIQUE,
  card_commission_percentage numeric NOT NULL DEFAULT 0 CHECK (card_commission_percentage >= 0::numeric AND card_commission_percentage <= 100::numeric),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branch_settings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_branch_settings_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_branch_settings_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.branch_fixed_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['RENTA'::text, 'NOMINA'::text, 'SERVICIOS'::text, 'MARKETING'::text, 'MANTENIMIENTO'::text, 'SEGUROS'::text, 'IMPUESTOS'::text, 'OTROS'::text])),
  concept text NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branch_fixed_costs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_branch_fixed_costs_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_branch_fixed_costs_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.employee_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  pin_hash text NOT NULL CHECK (length(pin_hash) > 20),
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT fk_employee_credentials_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.auth_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text,
  event_type text NOT NULL,
  ip_address text,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT auth_audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  title text NOT NULL,
  description text,
  severity text NOT NULL DEFAULT 'MEDIUM'::text,
  is_resolved boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT security_alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.system_settings (
  key character varying NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_settings_pkey PRIMARY KEY (key),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.sync_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sync_date date NOT NULL,
  status character varying NOT NULL,
  message text,
  results jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cash_closures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  close_date date NOT NULL,
  opened_by uuid,
  closed_by uuid,
  opening_cash numeric DEFAULT 0,
  declared_cash numeric DEFAULT 0,
  pos_terminal_sales numeric DEFAULT 0,
  cash_sales numeric DEFAULT 0,
  cash_ins numeric DEFAULT 0,
  cash_outs numeric DEFAULT 0,
  total_tickets integer DEFAULT 0,
  status_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cash_closures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  name text NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shifts_pkey PRIMARY KEY (id),
  CONSTRAINT shifts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT shifts_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.shift_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shift_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT shift_assignments_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT shift_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT shift_assignments_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id)
);
CREATE TABLE public.attendance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  shift_id uuid,
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  check_in_at timestamp with time zone,
  check_out_at timestamp with time zone,
  photo_url text,
  status text NOT NULL DEFAULT 'PENDING'::text CHECK (status = ANY (ARRAY['PENDING'::text, 'ON_TIME'::text, 'LATE'::text, 'ABSENT'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT attendance_logs_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT attendance_logs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT attendance_logs_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id)
);